version: '3'
services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./build:/etc/nginx/html"
    ports:
      - "80:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge